services:
  php:
    container_name: busca-app-php
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    working_dir: /var/www/html/laravel-app
    volumes:
      - ./laravel-app:/var/www/html/laravel-app
    networks:
      - busca_app_network

  nginx:
    container_name: busca-app-nginx
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./laravel-app:/var/www/html/laravel-app
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - busca_app_network

  mysql:
    container_name: busca-app-mysql
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: busca-app
      MYSQL_USER: busca-app
      MYSQL_PASSWORD: busca-app
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - busca_app_network

  node:
    container_name: busca-app-node
    image: node:22
    restart: unless-stopped
    working_dir: /var/www/html/laravel-app
    volumes:
      - ./laravel-app:/var/www/html/laravel-app
    ports:
      - "5173:5173"
    entrypoint: ["npm", "run", "dev"]
    command: ["sh", "-c", "npm install && npm run dev"]
    networks:
      - busca_app_network

volumes:
  dbdata:
    driver: local

networks:
  busca_app_network:
    driver: bridge